### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by toocool** [toocool/tripexpress#34]
- [ ] Front-end side for clients to view the timetable and make reservations
- [ ] Integrate online payment methods for clients
- [ ] flexible tour seats (two options: pre-defined seats & flexible)
- [ ] option to generate automatically tours for administrator pre-defined days
